apiVersion: skaffold/v2beta3
kind: Config
deploy:
  kubectl:
    manifests:
      - infra/k8s/*
build: ## 변경사항이 있을 때 마다 docker hub에 push 하지 말라
  local:
    push: false
  artifacts:
    - image: hyeongeol/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync: ## skaffold가 동기화를 바라보는 경로를 정의
        manual:
          - src: 'src/**/*.ts'
            dest: .
